language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - tip

install:
    # Basic go errors
    - go build -v ./...

script:
    # Check for format errors
    - errorCount=$(gofmt -l mediatype.go | wc -l); exit $errorCount

    # Run tests
    - go test -v ./...

matrix:
    allow_failures:
        - go: tip
    fast_finish: true
