language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - tip

install:
    # Basic go errors
    - go build -v ./...

    # Lint
    - go get github.com/golang/lint/golint

script:
    # Check for format errors
    - errors=$(gofmt -l .); echo $errors; (exit $([ "$errors" == "" ]))

    # Lint
    - golint ./...

    # Run tests
    - go test -v ./...

matrix:
    allow_failures:
        - go: tip

    fast_finish: true
